before:
  hooks:
    - make test
builds:
  - dir: ./task/bq2bq
    main: .
    id: "bq2bq"
    binary: "optimus-bq2bq_{{.Os}}_{{.Arch}}"
    ldflags:
      - -s -w -X main.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macos
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - src : ./task/bq2bq/optimus-plugin-bq2bq.yaml
        dst : "."
        strip_parent: true

release:
  prerelease: auto
  draft: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{.Version}}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^build:'
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "docker.io/gotocompany/optimus-task-bq2bq-executor:latest"
      - "docker.io/gotocompany/optimus-task-bq2bq-executor:{{ .Version }}"
    dockerfile: ./task/bq2bq/executor/Dockerfile
    extra_files:
      - task/bq2bq/executor

# brews:
#   - name: optimus-plugins-goto
#     tap:
#       owner: goto
#       name: taps
#     license: "Apache 2.0"
#     folder: Formula
#     description: "Optimus Plugins for warehouse"
#     skip_upload: auto
#     dependencies:
#       - goto/taps/optimus
#     commit_author:
#       name: github-actions[bot]
#       email: 41898282+github-actions[bot]@users.noreply.github.com
#     install: |
#       bin.install Dir["optimus-*"]
