name: build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-max2max:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22
      # Build the Go binary
      - name: Build
        run: |
          cd max2max
          mkdir build
          go get .
          env GOOS=linux GOARCH=amd64 go build -o ./build/max2max .
