name: release

on:
  push:
    tags:
      - 'bq2bq/v*'

jobs:
  bq2bq:
    if: startsWith(github.ref, 'refs/tags/bq2bq/v')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Extract the Git tag version
      - name: Extract tag version
        id: vars
        run: |
          # Extract the tag name from GITHUB_REF, remove 'refs/tags/bq2bq/' prefix
          TAG="${GITHUB_REF#refs/tags/bq2bq/}"
          echo "Tag name: $TAG"
          echo "::set-output name=tag::$TAG"
      # Build and push the Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./bq2bq
          platforms: linux/amd64  # Specify the target platforms
          push: true
          tags: |
            docker.io/gotocompany/optimus-task-bq2bq-executor:latest
            docker.io/gotocompany/optimus-task-bq2bq-executor:${{ steps.vars.outputs.tag }}
      - name: Log out from Docker Hub
        run: docker logout